name: Deploy Javadoc

on:
  push:
    branches:
      - master
      - main

jobs:
  javadoc:
    runs-on: ubuntu-latest
    permissions:
      pages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - run: chmod +x gradlew
      - run: ./gradlew dokkaGeneratePublicationHtml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.TOKEN }}
          publish_dir: ./build/dokka/html